# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IP\u5730\u5740')),
                ('STATE', models.CharField(choices=[('down', '\u8bbe\u5907\u5df2\u5173\u673a'), ('up', '\u8bbe\u5907\u5f00\u673a'), ('avi', '\u6b64IP\u672a\u5206\u914d')], max_length=30, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('MODEL', models.CharField(blank=True, choices=[('fwq', '\u666e\u901a\u670d\u52a1\u5668'), ('gmszx', '\u9ad8\u5bc6\u56db\u5b50\u661f'), ('ups', 'UPS'), ('ccjd', '\u5b58\u50a8\u8282\u70b9'), ('others', '\u5176\u4ed6')], max_length=30, verbose_name='\u578b\u53f7')),
                ('IDD', models.CharField(blank=True, max_length=30, verbose_name='\u8bbe\u5907\u7f16\u53f7')),
                ('USER', models.CharField(blank=True, max_length=30, verbose_name='\u8bbe\u5907\u4f7f\u7528\u8005')),
                ('TEL', models.CharField(blank=True, max_length=30, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('LOC', models.CharField(blank=True, max_length=30, verbose_name='\u8bbe\u5907\u4f4d\u7f6e')),
                ('NOTE', models.CharField(blank=True, max_length=30, verbose_name='\u5907\u6ce8')),
                ('TIME', models.DateTimeField(auto_now_add=True)),
                ('IPMI', models.CharField(blank=True, help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IPMI\u5730\u5740')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IP\u67e5\u8be2',
            },
        ),
    ]
